name: Security Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Build Docker Image (If applicable)
      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Trivy - Scan the built Docker image for vulnerabilities
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "myapp:latest"
          format: "table"
          exit-code: 1 # Fail the pipeline if vulnerabilities are found
          ignore-unfixed: true

      # Install Semgrep (Static Code Analysis)
      - name: Install Semgrep
        run: |
          pip install semgrep

      # Run Semgrep Security Scan
      - name: Run Semgrep SAST
        run: |
          semgrep --config p/security-audit --error --json .

      # OPTIONAL: OWASP ZAP for DAST (Run if app is running)
      - name: Run OWASP ZAP scan
        run: |
          docker run -u zap -p 8089:8081 -v $(pwd):/zap/wrk/:rw -i zaproxy/zap-stable zap-baseline.py \
            -t http://host.docker.internal:8080 \
            -r zap_report.html
